---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/sign-up":
    post:
      summary: creates User
      tags:
      - Authorization
      parameters: []
      responses:
        '200':
          description: Creates user
          content: {}
        '409':
          description: doesnt create
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
