---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/sign-up":
    post:
      summary: creates User
      tags:
      - Authorization
      parameters: []
      responses:
        '200':
          description: Creates user
          content: {}
        '409':
          description: doesnt create
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/auth/sign-in":
    post:
      summary: Login user
      tags:
      - Authorization
      parameters: []
      responses:
        '200':
          description: sign in user
          content: {}
        '401':
          description: doesnt create
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/auth/auto-login":
    post:
      summary: auto login
      tags:
      - Authorization
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: return user
          content: {}
        '401':
          description: doesnt create
          content: {}
  "/api/v1/posts":
    get:
      summary: List of posts
      tags:
      - Posts
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: list of teams shown
          content: {}
    post:
      summary: Create post
      tags:
      - Posts
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: return user
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: integer
                title:
                  type: string
                body:
                  type: string
              required:
              - title
              - body
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
